WarlockMud/mudlet-scripts

warlock.trigger.xml
=> Okienkowa wersja Garagotha

README.md
Jak w tytule - bez zmian kodu i funkcjonalności
=> Poprawiony plik README.md - dodanie dłuższego opisu, linków oraz instrukcji obsługi

skrypty.lua, statystyka/cechy.lua, warlock_scripts.xml
To jest niesamowicie prymitywny hardcode, ale zeby nie wycinało linii, niech jest poki co
=> Poprawki na dobrze zbudowany/a - PR na /fake

skrypty.lua, warlock_scripts.xml
/fake dla potomności
wyłączone dziwne kolorowanie które nic nie robiło w 'cechy'
=> /fake dla symulowania komend

aliases/aliases.lua, statystyka/cechy.lua, warlock_scripts.xml
- boskie i polboskie cechy sie dobrze licza
- alias /team do zresetowania okna
- kondycja jest juz dobrze wyswietlana w tym specyficznym przypadku gdy sie laczylo z regexem dla cech
=> Rozne drobne

scriptsList.lua, statystyka/opisy_poziomow.lua, triggers/spece.lua, triggers/walka.lua, warlock_scripts.xml
Tadam
i tak dalej. Dopasowane do obecnych kolorów ciosów
=> Spece dla szermierza

warlock_scripts.xml
To ogromna poprawka. Koloruje linie z wyjsciami w Chmurnych
=> Wyjscia w Chmurnych

gmcp/gmcp_Attack.lua, gmcp/gmcp_Init.lua, gmcp/gmcp_Kill.lua, gmcp/gmcp_Objects_Data.lua, gmcp/gmcp_Objects_Nums.lua, gmcp/gmcp_Room_Info.lua, gmcp/gmcp_Room_Leave.lua, gmcp/gmcp_Vitals.lua, okienka/stats_groups.lua, okienka/utils.lua, scriptsList.lua, skrypty.lua, walka/walka.lua
Okienko kondycji powinno już być mniej wadliwe.
=> Nowe eventy gmcp, rysowanie okienka kondycji

statystyka/cechy.lua
=> Poprawka do wielokrotnych cech

warlock_scripts.xml
Mini poprawka regexów w triggu "cechy" tak żeby nie łapały oceny cech przy medytowaniu.
=> Mini poprawka regexów w triggu "cechy".

scriptsList.lua, triggers/gonienie.lua, warlock_scripts.xml
Praca nad tym kosztowała mnie zgona. 🤣 
Dodałem takie strzałki:
=> Rysowanie strzałek w przypadku ucieczki mobków i graczy.

skrypty.lua
Podbicie wersji przed release.
=> Version bump

mapper/speedwalk.lua, skrypty.lua, statystyka/opisy_poziomow.lua, triggers/gonienie.lua, triggers/mowienie.lua, triggers/prompt.lua, triggers/spece.lua, warlock_scripts.xml
- anty idler timer fix
- poprawa podmiany poziomów (zły katalog folderów)
- wykrywanie mowy szeleszczących półorków
- poprawa prefixu speców szerzmierzy
- bugfix usuwania promptu
- zmiany i rozwinięcie funkcji na wyjąscia specjalne (można zbindować do 4 funkcji, mała zmiana logiki w przypadku zbyt wielu wyjść)
- łatwiej widoczny kolor szeptania naszego i do nas
- poprawki strzałek pogoni - łapie drużyny
=> Zmiany i poprawki. Bump do wersji 2.1.4.

skrypty.lua, triggers/ekwipunek.lua, warlock_scripts.xml
Ocena broni i zużycia.
Wyłapywanie mamrotania.
Kolejny bugfix oceny cech,
Dodanie magii runicznej do podstawowych kolorków czarów.
Ponowne ukrycie anty idla.
Usunięcie podmiany tabów.
=> Ocena broni + inne poprawki.

init.lua, mapper/speedwalk.lua, okienka/czat_windows.lua, okienka/okno_kondycji.lua, okienka/startup.lua, scriptsList.lua, skrypty.lua, triggers/ekwipunek.lua, utils/invalid_command.lua, walka/manewry.lua, walka/walka.lua, warlock_scripts.xml
=> Nowe okno kondycji, rozmaite bugfixy, invalid command, czas przetrwania itemków, version bump do 2.1.6.

warlock_scripts.xml
=> Kolorki, gagi by Gal

okienka/okno_kondycji.lua, walka/manewry.lua, walka/walka.lua
Bug z nowymi mobkami i migającym oknem.
Bug z szeregiem 10.
Lowercase do zasłon.
=> Bugfixy i drobne poprawki do okna kondycji i manewrów. 

warlock_scripts.xml
=> Poprawki w Galowych

skrypty.lua, triggers/podmiana.lua, warlock_scripts.xml
Kolorowanie poziomów umiejętności by gnomidlo.
Version bump.
=> Kolory umiejętności.

triggers/ekwipunek.lua
Dodane kolory, i poprawki przy sortowaniu
=> Poprawki estetyczne w plecaku 'Smotiego'

okienka/startup.lua
Reverts WarlockMud/mudlet-scripts#61
=> Revert "Update startup.lua"

gmcp/gmcp_Kill.lua, skrypty.lua, statystyka/cechy.lua, statystyka/counter/counter.lua, statystyka/opisy_poziomow.lua, triggers/spece.lua, triggers/walka.lua, walka/manewry.lua, warlock_scripts.xml
Poprawka liczenia killi w przemianie druidzkiej.
Dodanie % do licznika killi.
Dodanie statystyki defensow.
Dodanie stats i avg stats do licznika cech.
Poprawki w kolorowaniu specow i ciosow.
Poprawki kolorowania defensow.
Poprawki wylapywania defensow w przemianie druidzkiej.
Blokada ataku na najmow, konie i przywolance przy wylaczonym PVP.
Version bump.
=> Nowe statystyki i rozmaite poprawki.

mapper/mapper.lua, skrypty.lua
Naprawiony błąd z zapisywaniem przejść specjalnych.
=> Quickfix mappera
